version: "3.1"

volumes:
  prometheus-vol:
  grafana-vol:

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-vol:/prometheus
      - ${CONFIG_ROOT}/monitoring/prometheus/config:/etc/prometheus/
    network_mode: "host"
    restart: unless-stopped
  pve_exporter:
    image: prompve/prometheus-pve-exporter
    container_name: prometheus-pve-exporter
    volumes:
      - ${CONFIG_ROOT}/monitoring/exporters/pve/config/pve.yml:/etc/pve.yml
    ports:
      - 9221:9221
    restart: unless-stopped
  snmp_exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    ports:
      - 9116:9116
    restart: unless-stopped
  blackbox_exporter:
    image: blackbox-exporter-icmp:latest
    container_name: blackbox-exporter
    user: root
    network_mode: "host"
    volumes:
      - ${CONFIG_ROOT}/monitoring/exporters/blackbox/config:/config
    cap_add:
      - NET_RAW
    command: --config.file=/config/blackbox.yml
    restart: unless-stopped
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    volumes:
      - grafana-vol:/var/lib/grafana
    ports:
      - 5000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,grafana-piechart-panel
    restart: unless-stopped
  unpoller:
    image: golift/unifi-poller:latest
    container_name: unpoller
    ports:
      - 9130:9130
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_PROMETHEUS_NAMESPACE=unifi_metrics
      - UP_UNIFI_DEFAULT_USER='${UNIFI_USERNAME}'
      - UP_UNIFI_DEFAULT_PASS='${UNIFI_PASSWORD}'
      - UP_UNIFI_DEFAULT_SAVE_DPI=true
      - UP_UNIFI_DEFAULT_SAVE_SITES=true
      - UP_UNIFI_DEFAULT_URL='${UNIFI_CONTROLLER_URL}'
      - UP_PROMETHEUS_HTTP_LISTEN=0.0.0.0:9130
    restart: unless-stopped
