version: "3.1"

volumes:
  pihole-vol-etc:
  pihole-vol-dnsmasq:

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD='${PASSWORD}'
    volumes:
      - pihole-vol-etc:/etc/pihole/
      - pihole-vol-dnsmasq:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    restart: unless-stopped
